### ISSUE TITLE
NetRocks: add codepages selection for Windows FTP with ANSI charset

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1198]
For connect to Windows Ftp with ANSI filenames need add selection of codepages to view/copy correct dir/filenames.

In screenshot windows FTP with ANSI cp1251 characters in filenames:
![image](https://user-images.githubusercontent.com/92621645/149743116-16520798-b2b3-427e-8673-095c1b142e48.png)

**Comment by unxed** [comment]
Until this is solved, you may try to use CurlFtpFS instead. It supports codepage specification: 
http://manpages.ubuntu.com/manpages/bionic/man1/curlftpfs.1.html
https://wiki.archlinux.org/title/CurlFtpFS

**Comment by unxed** [comment]
Updated far2l-fuse plugin to support FTP and ANSI charset. User `ftp_ansi://` as protocol instead of `ftp://` to enable ansi mode. Language of your system locale should correspond server's code page for this to work (you can also specify OEM/ANSI code pages used by far2l if you need, see [this commit](https://github.com/elfmz/far2l/commit/f77eb63c4adc9d27b56889f320afbd1f1a72dd48) for details).

https://github.com/unxed/far2l-fuse
