### ISSUE TITLE
escape bad UTF-8 sequences in viewer the same way as in editor

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1265]
for UX consistency

**Comment by unxed** [comment]
or maybe use mapping as in 15cc3bf for this if single char replacement is needed

**Comment by elfmz** [comment]
Whats wrong with current replacement character?
Escaping doesn't align well with viewer's logic (that rather hard to refactor), and mapping to private characters negatively affects rendering speed (in wx mode), which is important for viewer.

**Comment by unxed** [comment]
Can we at least make current viewer's replacement char look the same as mapping chars in vt?

If vt log appearence changes after opening log in viewer, its a bit confusing

**Comment by elfmz** [comment]
you mean terminal log opened by F3/CtrlShiftF3? But it doesnt change, it will show same chars recently added in VT

**Comment by elfmz** [comment]
BTW you can use `cat /dev/urandom` to see that

**Comment by unxed** [comment]
Ok, closing then!

Having 3 different ways to handle incorrect utf8 sequences looks a bit weired, but if there are reasons for that, let it be so :)

**Comment by unxed** [comment]
Ok, closing then!

Having 3 different ways to handle incorrect utf8 sequences looks a bit weired, but if there are reasons for that, let it be so :)

**Comment by elfmz** [comment]
Private-UTF-range characters rendered slower by wx backend due to they treated as double width. Well thats problem of WX backend, but hard to fix.
Escaping has advantage that it allows 100% recovery, but disadvantage that it increases decoded sequence length. Still escaping also uses private UTF-character that is affected by slowness too. So escaping used where its needed to make sure UTF8->UTF32->UTF8 transcoding will produce identical data.
Single replacement char is fast but not recoverable, but later not a problem for viewer. Also Viewer need to be deeply refactored to support 'encodings' where for 1 byte sequence decoded into multiple wchar-s. Currently using escaping approach in viewer causes lot of artifacts with scrolling, search positioning etc. I know that cuz already tried that :)
