### ISSUE TITLE
[improvement suggestion] Add switch on/off for Files highlighting

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1377]
I suggest add in **Files highlighting** switch **on/off** for **rule** (may be by keys +/-).

For me it need because now both highlight rules for **Executable** & extensions **"*.sh,*.py,*.pl,*.cmd,*.exe,*.bat,*.com"** has identical colors. In some situations it good, but sometimes need quickly show only Executable and be useful temporary off *.sh,... rule without delete it.

**Comment by ivanshatsky** [comment]
As a workaround, the following technique can be used. Duplicate the highlightning group defined by mask. For the second group set default file colors and enable filtering by file attributes with the executable attribute being set to "off":
![image](https://user-images.githubusercontent.com/17809980/200153228-5847005d-0c2c-4564-b30c-f24b0106249f.png)

To disable highlighting files without the executable attribute turn on "Continue processing" option for the first group, to enable highlighting turn that option on. This way you will be able to emulate desired on/off rule behavior:
![image](https://user-images.githubusercontent.com/17809980/200153247-23a9e867-309e-4174-a1ae-eedae6d0fa23.png)

Since the number of highlightning groups is generally unpredictable, to switch highlightning using a macro you can use an autofilter feature, available for (almost) every menu with the Ctrl-Alt-F keys combination. The whole macro will be looking something like
```
DisableOutput=0x1
Sequence=F9 o h CtrlAltF * . s h Enter o Enter Esc
```

**Comment by akruphi** [comment]
Done in #2206 Thanks @anta999
