### ISSUE TITLE
[improvement suggestion] Add Ctrl+Alt+F info in Folders history & History panels

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1415]
1) Now Folders history & History panels have not information about very usefull features - filtering by Ctrl-Alt-F :(

I suggest expand the hotkeys list: Up/Down,Enter,Esc,Shift-Del,Del,Ins,Ctrl-C,**Ctrl-Alt-F**

2) Also after type filtering text in the panel the main title disappear (see screenshot)
![0](https://user-images.githubusercontent.com/92621645/203031934-14ba7610-dcaa-43e4-afed-d2373113ce29.png)
Please correct it for title remain.

**Comment by elfmz** [comment]
1 Actually, Ctrl+Alt+F combination is not related to history but its works in _any_ menu.
2 This behavior consistent with FAR3 at least 3.0.5888 so not sure if its bug

**Comment by akruphi** [comment]
> 1 Actually, Ctrl+Alt+F combination is not related to history but its works in _any_ menu.

I many years use Far in Windows and now Far2l and only recently get advice about **Ctrl+Alt+F**. This fine feature deserves to have **clear & visible info** for **user** (even in F1 help from both History & Folders history folder menu I did not find any info about Ctrl+Alt+F :( ).

> 2 This behavior consistent with FAR3 at least 3.0.5888 so not sure if its bug

This behavior is not user-friendly now. For long filter text title may be truncate or disappear, but disappear menu title immediately for short (even 1 character) filtering text menu title not comfortable.

**Comment by elfmz** [comment]
Actually for me it also new) BTW there is also fundamental issue with Ctrl+Alt+F - it doesn't work under usual terminal as Ctrl+Alt+F and Ctrl+F are indistinguishable there, so there is proposition to 'rename' Ctrl+Alt+F to F7 and then add it to menu headers. F7 will consume less space and also i quickly checked and it seems there're no conflicts in menus for F7

**Comment by ivanshatsky** [comment]
Hiding menu title when turning autofilter on is default Far for Windows behavior since the autofilter feature was implemented so it should not be considered as a bug. I want to remind that far2l behaved the same way before [this](https://github.com/elfmz/far2l/pull/1240) PR was merged. The PR goal was to mimic [this](https://forum.farmanager.com/viewtopic.php?f=15&t=8463) Far for Windows macro behavior. However most likely there was no way to always preserve original menu title and that macro was only doing the best it can, preserving menu title when an autofilter string was empty (see `reTitle()` function in the `MenuAutoFilter.lua` file).

Back to the suggestion, my vote is for preserving menu title until the autofilter string fits its placeholder and hiding title only when it became too long. Adding an alternate F7 keyboard shortcut seems reasonable too.
