### ISSUE TITLE
[bug] Backslashes in Copy ... to  dialog

### ISSUE THREAD

**Issue by TrNullFree** [elfmz/far2l#1417]
Latest far2l build (version 2.4.1-9e57af5a-beta)

1. open far2l
2. create folder with space(s) in name like "Intel Driver"
3. select any file and press F5
4. type Int in "Copy ... to:" field
5. field auto expands to "Intel\ Driver"

**Comment by TrNullFree** [comment]
What about this bug?

**Comment by akruphi** [comment]
This is not quiet documented far2l features. Also by **Ctrl+Enter** or **Ctrl+F** it add escaping `\` before spaces (because in Linux ' or " available symbols in filenames).

May be add in far2l Options toggle for this behavior for filenames:
- Escape all spaces by \
- Never Escape spaces
- Enclose filenames with spaces in double quotes "
- Enclose filenames with spaces in quotes '

**Comment by TrNullFree** [comment]
Fixed by #2081
