### ISSUE TITLE
[Improvement] Add Confirmation for Clear Terminal history and screen by F8

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1567]
Please add **Confirmation** for **F8** in **Terminal** a la other Clear history confirmations
and for it add separated checkbox `[x] Clear Terminal history & screen` in Menu->Options->Confirmations

**Comment by akruphi** [comment]
> Could consider as alternative 'restoring' of just erased by F8 log by repeated press on F8? (And remembered content will be cleared by command execution of course)

For newbie far2l users confirmation panel is more expected & user-friendly because short `8Delete` in key bar not explain all nuance and many users not look in help. But if confirmation has some difficulties in Terminal logic your suggestion may be good.

May be also in Terminal in key bar change `8Delete` to `8Clear`?

**Comment by ivanshatsky** [comment]
Having an experience of occasionally deletion important console output (pressing F8 instead of F4) I agree that it would be very nice to have this confirmation added to "Confirmations" dialog (enabled by default). I agree with @akruphi that "undoing" this operation pressing F8 again looks counter-intuitive, having a confirmation would be better.

And since we discussing console here, yet another question. Is it too hard to implement an option for console lines amount instead of being hardcoded as `5000` in `vtlog.cpp`? Or at least make it customizable with CMake flag? (I always change this value to `10000` building `far2l`).
