### ISSUE TITLE
Options->Confirmations->Delete non-empty folders - not working

### ISSUE THREAD

**Issue by Gravityzwell** [elfmz/far2l#157]
"Options->Confirmations->Delete non-empty folders" seems to have no effect. Confirmation always appears. Also, confirmation appears for empty folders.

**Comment by elfmz** [comment]
Its working. Actually when option is off - there is one confirmation, when its on - there're two confirmations, and second one is red:
![image](https://cloud.githubusercontent.com/assets/20957349/19619843/81c951f6-9878-11e6-84c6-80731f06a817.png)
And such logic existed in Windows FAR (and exists in FAR2), so it looks by design, unless you see some different behaviour.

**Comment by Gravityzwell** [comment]
Confirmed this is the Far2 behavior (I didn't realize). If you want to just follow Far2, then OK.

Far3 will not prompt if both "Delete" and "Delete non-empty folders" are unchecked. This is what I expected (and prefer).

Also, Far2 prompts when deleting an empty folder, even when both "Delete" and "Delete non-empty folders" are unchecked. I don't see how this makes sense.
