### ISSUE TITLE
Colorer: wrong highlight

### ISSUE THREAD

**Issue by SerjCh** [elfmz/far2l#158]
Checked XHTML Strict, XML. Attached screenshot of same html file opened by far2l & Far 3 (I think Colorer approx equal)
![screenshot from 2016-10-20 22-51-02](https://cloud.githubusercontent.com/assets/19835749/19575614/2df134b0-9718-11e6-8b5b-318b1ed3b75e.png)

**Comment by elfmz** [comment]
1) does this happen with all html or only some? (I tested couple - works fine)
2) looks like a strange question, but tell please what gcc version you used to compile far2l (gcc --version)

**Comment by eliah** [comment]
@elfmz - I have the same problem with colorer (*Far Manager, version 2.1 (build 16/10/20-fc5501e) Darwin x86_64*). HTML works fine, but all xml-based types are colored like on attached picture.

Also, I had small problems with the perl syntax highlighting, but solved it by changing one of definitions in `common.jar`:

`base/perl.hrc:236      <entity name="PerlData" value="__(?{}END|DATA)__|[\x1A\x04]"/>`
to
`base/perl.hrc:236      <entity name="PerlData" value="__(?{}END|DATA)__"/>`

Maybe it will help to find a source of the problem. Looks like some sort of wrong encoding translation of regexps.

Also, in colorer, when selecting types, arrow up selects the type instead of moving the cursor one position up, so I use left and right arrows to move cursor up and down.

**Comment by SerjCh** [comment]
@elfmz 
1. I think, as written above by @eliah , all xml-based. But may be affected other formats, need to recheck. Attached checked xhtml file.
[login.html.zip](https://github.com/elfmz/far2l/files/543706/login.html.zip)


2. gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
