### ISSUE TITLE
MacOS: far2l captures keystrokes from other applications

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#1580]
Under MacOS:
1. Press Enter on a .jpg image, this will launch a viewer (XnView, which closes the application when the last window closes).
2. Press Cmd-W.

Expected result: Preview window closes. OS has moved focus is back in Far.
Actual result: Preview window closes. OS has moved focus is back in Far. Far processes Cmd-W and launches `htop`.

This happens to every shortcut that happens to close another application, and Far is focused. Cmd-Q is the worst.

Shouldn't the shortcuts only receive key-down events? I know some functions process other events, but this is not the case.

**Comment by unxed** [comment]
Do you use tty, ttyx or wx backend? Has this started happening recently, or has it always been like this?

**Comment by singalen** [comment]
wx. It feels like it’s been like this for a very long time.

**Comment by elfmz** [comment]
Indeed macos sends keyup to far2l in such situation. What worse that those keyups cannot be just ignored even though they're unmatched with corresponding keydown due to https://github.com/elfmz/far2l/blob/master/WinPort/src/Backend/WX/wxMain.cpp#L1231
But seems ignoring such unpaired keyups during first 100msec after getting focus should be good workaround. Please check current master if it resolved this for you..

**Comment by singalen** [comment]
Seems to work for me. Thanks a ton!
