### ISSUE TITLE
Rename/move of large folders (1k+ files/subfolders) should be done momentary, there is no need to rename each subfolder/file one by one

### ISSUE THREAD

**Issue by alexandrustinov** [elfmz/far2l#1683]
How to reproduce 

Select large folder with lot of subfolders/files(>1k+) then press F6 and put new name (just add few chars).

Actual behavior -  far2l tries to move each subforder/file with progress indicator
Expected behavior - the top level folder name rename should happen momentary, as far as there is no need to enumerate all those subfolders and files and rename each of them one by one, we just need to perform top level folder rename

Note - when the top level folder is being moved from one place to another but in bounds of the same mountpoint/device  - it also should be done momentary, just like command `rn` does that. 
Symlinks and multiple mounts of the same device also should be resolved accordingly.

**Comment by alexandrustinov** [comment]
https://pubs.opengroup.org/onlinepubs/000095399/functions/rename.html
https://man7.org/linux/man-pages/man2/rename.2.html

rename() function will return EXDEV if the files reside in different filesystems - after that it makes sense to fallback to current "one by one rename" implementation.

That assumption about "try rename() first then fallback to own implementation" could be true for other error codes, while EACCES should be retried using sudo escalation window, if that is applicable for current user.

**Comment by unxed** [comment]
Try experimenting with the "with symlinks" settings. When you select one of them, in theory, the entire folder should be renamed at once.

**Comment by alexandrustinov** [comment]
I tried - select folder with 30k+ subfolders/files, then Shift+F6, With symlinks dropdown
- Always copy link - far2l enumerates all the subfolders/files (why?) then performs top-level rename, looks reasonable
- Smartly copy link or target file - it shows progress bar for all the files
- Always copy target file - it shows progress bar for all the files

Those options look a bit unexpected and not intuitive, expecially the "smart option" for rename. 
It might be true for copy, but even there not as default option.

Technically user expects from F6 and F5 the same behavior as it was available for `mv` and `cp` commands, those "smart options" by default could be dangerous.

Is it possible to enable the "Always copy link" by default?

**Comment by akruphi** [comment]
The influence symlink settings on instant action or file-by-file action is very interesting but this feature and speed is not intuitive.

I not fully agree with @alexandrustinov that "Always copy link" may be preferable for default, because in some situation "Smartly copy" more useful.
Now this parameter works on both copy and move actions and stored in `~/.config/far2l/settings/config.ini` as line `HowCopySymlink=1` and default value set in https://github.com/elfmz/far2l/blob/01c821c513f74b355584985f65753d7e3a25d475/far2l/src/cfg/ConfigSaveLoad.cpp#L369 and works on both copy and move actions.

I think may be add short comment in combo box items. For example in https://github.com/elfmz/far2l/blob/master/far2l/bootstrap/scripts/farlang.templ.m4 :
`Всегда копировать &ссылку` -> `Всегда копировать &ссылку (быстро)`
`Always copy &link` -> `Always copy &link (fast)`

`&Умно копировать ссылку или файл (медленно)`
`&Smartly copy link or target file` -> `&Smartly copy link or target file (slow)`

`Копировать как &файл` -> `Копировать как &файл (медленно)`
`"Always copy target &file"` -> `Always copy target &file (slow)`

@elfmz please explain whether the terms fast and slow are applicable & correct here for copy and move process in far2l.

**Comment by alexandrustinov** [comment]
> The influence symlink settings on instant action or file-by-file action is very interesting but this feature and speed is not intuitive.
> 
> I not fully agree with @alexandrustinov that "Always copy link" may be preferable for default, because in some situation "Smartly copy" more useful.

Could you give any example, where implicit converting symbolic link into physical file may be useful? 
As for me that behavior is not expected and dangerous, for an example it can produce tons of .so files (which normally should be always symlinks) which will be never updated by security patches just because they don't point to proper and updatable place anymore but hold own binary copy instead, and no-one is aware about that anymore.

Symlink must be always kept as symlink. Rare case of broken symlinks should be manually fixed by repointing them to proper place, that issue is not related to folder copy/rename operations.

**Comment by akruphi** [comment]
> Could you give any example, where implicit converting symbolic link into physical file may be useful?

I wrote for often useful now default far2l options **Smartly copy link**, which describe in far2l help:
```
   - Either far2l will check each symlink target to find out if it refers 'outer' file or some file
also being copied. In first case link will be copied as file, in second it will be copied as symlink
with possible adjusted destination, so it will refer copied target file.
```
It behavior very useful for copy to other mount partition (and then transfer it to other computer) or copy to/from network location.

May be in these cases sometimes more preferable _not silent smart copy_ but add variant **Smartly (with warnings) copy...** with show warning dialog with variants of actions (stay symlink without changes, correct symlink to relative in new location, copy target file) or after copy list of corrected symlinks (in temporary panel)?

I agree that **topic started situation** is **really not intuitive in far2l** for users. I think more delicate correction will be expand in dialog box items by short suffix texts `(fast)` or `(slow)` and more details describe in help.
