### ISSUE TITLE
why do we need to store registry key name in the first line of v-* files if it already presents in the file's name?

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#178]
unneeded duplication always cause confusion and potential errors.

if I change key name inside file, but leave file's name unchanged, what value would be used?

**Comment by unxed** [comment]
and the record's type can also be stored as v-* file's extention. for example:

v-UsePromptFormat.DWORD

**Comment by elfmz** [comment]
Because in windows registry names are case insensitive. Linux FS is case sensitive. So in order to behave exactly as under Windows - all filenames should be converted in lower case. BUT application logic may require names to be enumed with exact names as they were stored. So exact named information should not be lost. Thats why value name is inside of its filename. The reason why filenames are not low-cased - is only my lazyness and fact that I didn't want to achieve 100% compatibility with Windows. But it this once be required - it can be easily 'upgraded' without losing old data.

**Comment by unxed** [comment]
> in order to behave exactly as under Windows - all filenames should be converted in lower case

does this actually affects anything? if not, is this windows-like behavour really required?

**Comment by elfmz** [comment]
Record type can't be part of filename. Registry doesn't allow creating several names with same name but different type. Putting record name to file name will make it possible.

**Comment by unxed** [comment]
I also found this potential ambiguity in my approach. Possible solution: if there are many files with the same name and different extensions, the most recent one (by file's last write date/time) should be used, and the others must be removed, I guess.

**Comment by elfmz** [comment]
There is no need to find new solution if current works well.

**Comment by unxed** [comment]
ok, you can close this as WONTFIX then :)

**Comment by elfmz** [comment]
/*does this actually affects anything? if not, is this windows-like behavour really required?*/
Once again. Currently it works well. But if this will be necessary in future this little reservation will allow painless 'upgrade' logic without losing application settings and without implementing additional 'data upgrade' code.

**Comment by unxed** [comment]
ok, you can close this as WONTFIX then :)

**Comment by elfmz** [comment]
there is only option 'close and comment', so I will use it)
