### ISSUE TITLE
Flashing upon executing cd command in command prompt

### ISSUE THREAD

**Issue by dagolinuxoid** [elfmz/far2l#1824]
When panels are used to navigate to a certain path (via pressing Enter) changing is snappy. However upon executing something like `cd ~/Videos` doesn't look that smooth - there is a some delay (it's very quick but noticeable) and flashing of an interface occur upon transitioning when used change directory command in command prompt.

**Comment by elfmz** [comment]
Its becase running cd command really executes it in terminal and then directory being retrieved from shell that runs in terminal and reflected back to panels.
This is different to how Windows FAR behaves, where 'cd' command is handled completely by FAR itself. And its intentional, cuz it handles not only simple 'cd /some/path' but also any complex shell expression, that results in directory change, like `echo hello; export FOO=/home; cd $FOO; echo world`

**Comment by dagolinuxoid** [comment]
Thanks, just wanted to be make sure of it. I can live with it :)
