### ISSUE TITLE
mac shell: command not found

### ISSUE THREAD

**Issue by voronczoff** [elfmz/far2l#1900]
when trying to launch anything from builtin far2l shell i get: command not found

~$ 7z
/var/folders/sw/082kg9zn34n8d85y0f8fh7v40000gn/T/far2l_1f5_0/vtcmd/fa49_2:5: command not found: 7z

both zsh and bash locate 7z normally

far2l 2.52 sonoma m1

**Comment by nZeus** [comment]
It works fine if you install via brew `brew install --HEAD yurikoles/yurikoles/far2l`

**Comment by vyuzhanin** [comment]
@voronczoff have you installed 7z from homebrew?

it seems that no one console util that installed from homebrew doesn't work. It works fine when far2l built on intel but for arm64 it has an issue.

It should be added  `/opt/homebrew/bin` to PATH environment.

**Comment by voronczoff** [comment]
yes, i installed thru homebrew, file resides here:
/opt/homebrew/bin/7z
and /opt/homebrew/bin is in TEMP env var

btw it works within far2l cli, problem is only with casked far2l.app

**Comment by vyuzhanin** [comment]
If you will try to run `echo $PATH` from far cmd line you won't find `/opt/homebrew/bin` but from ITerm or ITerm2 the value is exists. That is the main issue.

**Comment by voronczoff** [comment]
> If you will try to run `echo $PATH` from far cmd line you won't find `/opt/homebrew/bin` and `/opt/homebrew/sbin` but from ITerm or ITerm2 the values is exists. That is the main issue.
> 
> To fix the issue you have to run `eval "$(/opt/homebrew/bin/brew shellenv)"` each time you start far2l OR add that line to the ~/.bashrc or ~/.zhrc file.

Thank you! Added it to rc files, now everything is fine!

**Comment by vyuzhanin** [comment]
The final issue is because far2l totally ignores `~/.bash_profile` and `~/.zprofile` files. In macOS case the [Homebrew installation script](https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh) sets necessary environment vars to that files:

<img width="414" alt="image" src="https://github.com/elfmz/far2l/assets/596514/dcbbb251-a848-4d54-9b08-dd413f25f4c8">

**Comment by atolismesh** [comment]
Please check the INVOCATION section in the Bash man on your system.
IMHO On a Linux /MacOS systems, bash does not use the .bash_profile file by default. Only if invoked as login shell.
Try changing the .bashrc file in your $HOME.

**Comment by vyuzhanin** [comment]
The issue is still reproduces:

<img width="1019" alt="image" src="https://github.com/elfmz/far2l/assets/596514/1ecd6399-cb99-449a-aad5-b02849abfd11">

**Comment by dodo-16** [comment]
Эта... А где можно Дарвиновский 2.6.0 поиметь? 😊

**Comment by AndrewElans** [comment]
On macOS I have default terminal-app zsh. 

I installed first [brew](https://brew.sh), then [fnm](https://github.com/Schniz/fnm) with brew, then node with fnm, then far2l with brew.

Since far2l on macOS works only with bash as explained [here](https://github.com/elfmz/far2l/issues/1925#issuecomment-1837395188), running `node -v` in far2l gives `bash: node: command not found`. Let's switch default terminal on macOS to bash instead of zsh with the command `chsh -s /bin/bash` and try there.

In bash-app I get `-bash: node: command not found`. I try `fnm` -> `command not found`, try `brew` -> same `command not found`. This has to do with some env variables that are different in zsh and bash. 

# To fix

For env variables, zsh uses `.zprofile` and `zshrc`, whereas bash app uses `.bash-profile` and `.bashrc` which I don't have. I found that bash does not create these by default.

Content of `.zprofile`: 
```bash
eval "$(/opt/homebrew/bin/brew shellenv)"
```

Content of `.zshrc`:
```bash
# fnm
export PATH="/Users/ae/Library/Application Support/fnm:$PATH"
eval "`fnm env`" 
```

In far2l I navigate to `Users/<my user>` and create two files: `.bash-profile` and `.bashrc`. In `.bash-profile` paste content of `.zprofile`, in `.bashrc` paste content of `.zshrc`. But it's not enough. 

As explained [here](https://apple.stackexchange.com/a/13019), I add `source ~/.bashrc` in the `.bash_profile` in addition, and now I can run all commands in far2l.
