### ISSUE TITLE
[Feature request] Add support of TIME_STYLE format for File panel modes and Set file attributes dialog

### ISSUE THREAD

**Issue by alexandrustinov** [elfmz/far2l#1942]
For Linux it's possible to set custom date/time format using env variable TIME_STYLE, please refer to details there:
https://www.gnu.org/software/coreutils/manual/html_node/Formatting-file-timestamps.html

you can see the effect using next commands

    ls -la --time-style=long-iso

or 

    env TIME_STYLE=long-iso ls -la

Kindly please consider to add such support for File panel modes setup and Set file attributes. 

I think it does not make much sense to split the Date and Time columns for that mode (File Panels). It's ok to have single Date/Time column with the TIME_STYLE format support.
Midnight commander does like that - it shows file timestamps in single column, using the ls format, it would be great to have the same for far2l.

**Comment by akruphi** [comment]
Far2l has inside code, which construct date/time for 3 DateFormat (DD.MM.YYYYY, MM.DD.YYYYY or YYYYY.MM.DD) and variable Date or Time Separators (functions `ConvertDate`, `st_time` from [far2l/src/datetime.cpp](https://github.com/elfmz/far2l/blob/master/far2l/src/datetime.cpp)). But now functions `GetDateFormat()`, `GetDateSeparator()` and `GetTimeSeparator()` return hardcore values.

It may relatively ease add in Settings dialog a choose of one of these predefined formats, because convert TIME_STYLE to now supported limited variants are not trivial.

What your opinion about such customization?

**Comment by akruphi** [comment]
After https://github.com/elfmz/far2l/commit/4751f6d0ff03dd66c27c06b9427d48f0618391b0 in Options->Interface settings you can manually customize date-time format.
