### ISSUE TITLE
Colorer: Error Schema

### ISSUE THREAD

**Issue by SerjCh** [elfmz/far2l#195]
![screenshot from 2016-11-08 00-01-29](https://cloud.githubusercontent.com/assets/19835749/20078069/c138a0b8-a547-11e6-999a-8a624e086a2b.png)

**Comment by elfmz** [comment]
please close far2l, then do rm -rf ~/.config/far2l/REG and start far2l see if problem still there

**Comment by SerjCh** [comment]
still here - https://www.youtube.com/watch?v=1bBkSbFxGu8

**Comment by elfmz** [comment]
Likely i know whats the problem. Its due to I renamed plugins location from bin to plug. So you have 2 colorers now, also 2 of each other plugins - old and new versions.
remove all far2l related stuff from /etc/far2l and /usr/lib/far2l
completely cleanup build directory (make clean is not enough), configure it with cmake and build from scratch

**Comment by SerjCh** [comment]
Now all fine :)

**Comment by elfmz** [comment]
ok, let issue hang here for a while for others..
