### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Molochnik** [elfmz/far2l#2116]
1) How to scroll through terminal output after Ctrl-O? Sometimes Wheel/PgUp/PgDown work, sometimes don't.
2) Ctrl+Enter puts the file name with prefix "./" to the command line even if it already contains the path

**Comment by spnethw** [comment]
1. F3 / F4 открывают историю терминала во вьювере / редакторе соответственно, такой вариант не подойдет?

2. Немного непонятно, что имеется в виду под "already contains the path", типа набрано в командной строке вручную? Так не надо вручную набирать (или, если полный путь нужен, ещё Ctrl-F есть).
Это вроде by design так, чтобы можно было, например, подставлять имена файлов как аргументы (а их может быть несколько)  для набранной в командной строке команды.

**Comment by Molochnik** [comment]
1) полностью! В голову ни разу не приходило что так может работать
2) Не вручную, Ctrl+] вставляет путь к правой панели, Ctrl+Enter имя файла, а вместе вместо полного пути, между ними точка оказывается

**Comment by Zeroes1** [comment]
@Molochnik по 2му всё правильно работает логика. одна комбинация даёт путь, вторая имя файла без анализа что там впереди.
если нужен полный путь нужно использовать другой хоткей Ctrl-F.

Ещё вариант перейти на Far2m с поддержкой LUA макросистемы там по CtrlEnter можно добавить анализ что впереди и скорректировать поведение.
