### ISSUE TITLE
File attribute dialog displays every user and group (except for the current user) twice in the dropdowns (macOS)

### ISSUE THREAD

**Issue by sirburpalot** [elfmz/far2l#2135]
I'm running the current snapshot of far2l (2.6.0-2024-04-08-e6ad61a1). The issue appears to be specific to macOS; Linux users are saying they don't have it.

Screenshot:

<img width="564" alt="user_duplication" src="https://github.com/elfmz/far2l/assets/1429516/b95d75b4-5f3f-4de5-8757-9813fcb54d1b">

**Comment by exkrexpexfex** [comment]
Far seems to use getpwent() when generating the list
Simple test on latest MacOS 
`	while ((pw = getpwent()) != NULL)
		std::cout << pw->pw_name << " " << pw->pw_uid << "\n";
`
shows duplicates when output is sorted
`daemon 1
daemon 1
nobody 4294967294
nobody 4294967294
root 0
root 0`

Documentation man getpwent states that the information is obtained from opendirectoryd 
With fairly default configuration with no external directories added
`% odutil show nodenames             
Nodenames:

Name              State  Refs Type External Locked Hidden 
----------------- ------ ---- ---- -------- ------ ------ 
/Active Directory Online 1                  X      X      
/Configure        Online 1                  X      X      
/Contacts         Online 3                                
/LDAPv3           Online 1                  X      X      
/Local            Online 2                  X      X      
/Local/Default    Online 63                 X             
/Platform SSO     Online 1                  X             
/Search           Online 26                               
`
username nobody is found in two locations
`
 % dscl localhost -list /Search/Users |grep nobody
nobody
 % dscl localhost -list /Local/Default/Users |grep nobody
nobody
`
That's probably the source of duplicates on Mac.
Also FreeBSD man page for getpwent explicitly states "The getpwent() and getpwent_r()  functions  make
       no  attempt  to	suppress duplicate information if multiple sources are
       specified in [nsswitch.conf(5)](https://man.freebsd.org/cgi/man.cgi?query=nsswitch.conf&sektion=5&apropos=0&manpath=FreeBSD+14.0-RELEASE)"
So the issue is not MAC-specific. It seems to be good to remove duplicates from the list obtained from getpwent
