### ISSUE TITLE
Double search and F4 cause file delete

### ISSUE THREAD

**Issue by asvzzzz** [elfmz/far2l#2223]
I encountered with such problem:
Sometimes you need to find a certain substring in the source files, and then another in these found files.
That is, in the folder with the files, press ALT+F7, the line “abcd” for example, search.
A list of found files with this string appears, click "Panel". Press ALT+F7, new substring "1234" for example, search.
A new list of files has appeared. In this list (without going to the "Panel" view) on any file, press F4, look at what you wanted, ESC, look at the next one, etc.
And all files opened using F4 during such double (triple, etc.) search will be DELETED!
I was upset after deleting some not committed files!
Version 2.6.1-2024-04-15-d6cc217-beta Linux x86_64

**Comment by akruphi** [comment]
Note: Inside https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L1474-L1700 has depended on variable `RemoveTemp` deleting temporary files in https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L1697

But in each press **F3** or **F4** `RemoveTemp` initialized as `false` and should no influence to real files.

**Comment by spnethw** [comment]
It seems that problem is really in [findfile.cpp](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp), but a little earlier in the code, namely here: https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L1673-L1679

if `FindItem.ArcIndex != LIST_INDEX_NONE`, then the instance of [FindDlg_TempFileHolder](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L1216) will be created. This class inherited from [TempFileUploadHolder](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/fileholder.hpp#L45), which in turn is inherited from [TempFileHolder](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/fileholder.hpp#L25) _(which in turn is inherited from [FileHolder](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/fileholder.hpp#L8))._

The actual  file deletion is done in the [TempFileHolder::~TempFileHolder()](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/fileholder.cpp#L44) which will be called as the base class destructor when the instance of `FindDlg_TempFileHolder` is destroyed:
https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/fileholder.cpp#L60-L66

**Comment by spnethw** [comment]
So, the problem is that the files found on a second search from "Temporary panel" are treated as temporary files, as if the search was done in an archive and they were extracted to /tmp.

**Comment by spnethw** [comment]
Оставить просто

 `TFH = std::make_shared<FileHolder>(strSearchFileName);` 

мы не можем, хотя бы потому что таким образом мы убьём одну из фич far2l — а именно сохранение сделанных при редактировании изменений обратно в архив. Так как в [ветке](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L1620), получающей управление при запросе на редактирование по F4, потом дёргается https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L1686

А она в базовом классе, FileHolder, [не имеет](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/fileholder.cpp#L30) реализации, а [реализована](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/fileholder.cpp#L115C6-L115C45) только в непосредственном предке FindDlg_TempFileHolder — в [TempFileUploadHolder](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/fileholder.hpp#L45) .

**Comment by spnethw** [comment]
Есть ощущение, что можно попробовать пофиксить, изменив логику где-то в этой области:
https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L2447-L2464

Именно тут функцией [AddArcListItem](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L248) файлы незаслуженно отправляются в [ArcList](https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L125) :
https://github.com/elfmz/far2l/blob/2068c4681098af1206156ca1297cc6cb9aa48721/far2l/src/findfile.cpp#L2454

Допустим, проверять, и если мы на tmppanel, а не multiarc, то всех этих телодвижений не выполнять?

**Comment by unxed** [comment]
> Допустим, проверять, и если мы на tmppanel, а не multiarc, то всех этих телодвижений не выполнять?

А сделайте PR мне в [staging](https://github.com/unxed/far2l/tree/staging), посмотрим как это у людей работать будет, если ничего нигде не сломается, зашлём сюда.

**Comment by akruphi** [comment]
Вроде #2229 исправляет без внесения новых глюков, но проверьте кто может крайние случаи и в них ситуацию перехода по **F6** между редактором и просмоторщиком и обратно.

**Comment by unxed** [comment]
Забрал в свою ветку staging, у неё отдельный ppa и там некоторое количество людей из чята на ней сидят. Поглядим, не будет ли жалоб.
