### ISSUE TITLE
New release request 

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2419]
Let's keep this issue open.

Colleagues, in Debian we have 2.6.3 with a bunch of glitches under WSL/WT, isn't it time to release 2.6.4?

@elfmz @alexmyczko

**Comment by m32** [comment]
Can someone tell me why python/plug/plugins is not packed into tar.gz and the directory in .deb is also empty?
The directory install/plugins/python contains everything needed but in the resulting file (.tar.gz .deb) the directory python/plug/plugins contains only subdirectories and no files
Am I making the package correctly?

I use the commands:
mkdir _build
cd _build
cmake .. -DLEGACY=YES -DUSEWX=YES -DEACP=NO -DEDITORCOMP=NO -DPYTHON=YES -DCMAKE_BUILD_TYPE=Debug
cmake --build . --target package

**Comment by m32** [comment]
there are also problems with installing the deb package, if I do not manually install:
apt install libminizip1 libwxgtk3.2-1 libwxbase3.2-1 libssh-4 python3-cffi python3-pycparser

this execution:
dpkg -i far2l_2.6.3-2024-10-06-e9095b85-beta_amd64.deb

it will show dependency errors

**Comment by unxed** [comment]
@elfmz we are ready now. Accepting the fix for #2294 would be nice, but not essential.

**Comment by unxed** [comment]
UPD :)

**Comment by elfmz** [comment]
how much time before deadline (if any) remain?

**Comment by akruphi** [comment]
> how much time before deadline (if any) remain?

IMHO **hard deadline** is **Debian Freeze** this winter (exact date hasn't been announced yet https://release.debian.org/trixie/freeze_policy.html , but previous was in January https://release.debian.org/bookworm/freeze_policy.html).

But now far2l was **removed from Debian testing** :crying_cat_face:  (see news in https://tracker.debian.org/pkg/far2l ), because 2.6.3 can not correct building in Debian's servers (some corrections PR https://github.com/elfmz/far2l/pull/2340 etc was after 2.6.3 release). To get back in, we need a release that builds correctly in Debian servers, plus ~10 days.

It's better to make a release **as soon as possible** to ensure everything builds and works correctly in Debian Testing, and to have a time for corrections and new releases before Debian winter freeze.

**Comment by akruphi** [comment]
May be make release immediately without all non-accepted waiting PRs (lets test and approve their after release)?

IMHO: we should give @alexmyczko release to building correct both `far2l` and `far2l-wx` and look at their behavior on all Debian architectures.

@elfmz @alexmyczko @unxed @spnethw what are your opinion?

**Comment by unxed** [comment]
> At least PR #2463 should be merged

Also https://github.com/elfmz/far2l/pull/2469 please as a minor bug was found after all.

**Comment by unxed** [comment]
@akruphi agree. As for me, it's ok to release after merging #2473

**Comment by akruphi** [comment]
@elfmz may be now fix only significant https://github.com/elfmz/far2l/issues/2492 and https://github.com/elfmz/far2l/issues/2494 and quickly make release because now it is preferable make Debian release with 1st-time **far2l-wx** package and we should has enough time before Debian winter freeze to receive users feedback and fix all possible problems in all architectures.

@alexmyczko please say your opinion.

**Comment by alexmyczko** [comment]
dunno i was waiting for release.. but i can't see one so going to do the current version without python...

**Comment by spnethw** [comment]
It's time...

**Comment by unxed** [comment]
Agree

**Comment by elfmz** [comment]
I verry sorry, i made 2.6.4 release and removed it with git push -f in 5..10 minutes later, hope wasnt cause too much false alarm.
Reason - under MacOS keyboard unusable - alot of key duplicated events

**Comment by elfmz** [comment]
Seems fixed but will take one day more to check that on mac all really good now

**Comment by unxed** [comment]
Возможно, до релиза стоит ещё #2498 поправить, там в тикете лежат патчи, PR не могу ща сделать

**Comment by akruphi** [comment]
@alexmyczko 2.6.4 Release done :tada:

**Comment by spnethw** [comment]
Close?
