### ISSUE TITLE
"Notify only in background" does not work

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#2563]
I have pulled latest version and just build far2l and it annoyingly shows notifications about every run command even when I am running it directly, without minimizing far2l. "Notify only in background" seems to have no effect, only when I disable notifications completely, they go away.

**Comment by unxed** [comment]
The reason is probably that far2l in tty mode does not knows the focus of terminal window status.
Possible solution is to track it using `\033[?1004l` [mode](https://unix.stackexchange.com/a/480138). Focus tracking should have 3 states:
- we have focus
- we do not have
- focus state is unknown (some terminals do not reporting current state)

Notifications should be sended only if we definitely do not have focus.

**Comment by unxed** [comment]
@Dazzar56 could you please help with adding this?

**Comment by spnethw** [comment]
At the moment there is just a stub here:

https://github.com/elfmz/far2l/blob/9ef3316e72fdf6ec57c5ff356888e55ed76a8bc7/WinPort/src/Backend/TTY/TTYBackend.cpp#L960-L963

**Comment by elfmz** [comment]
may change to `return _far2l_tty ? false : true;` as quick workaround

**Comment by elfmz** [comment]
..or better: #2567

**Comment by elfmz** [comment]
check current master please if you can

**Comment by unxed** [comment]
Works for me :)

**Comment by spnethw** [comment]
Works as expected in: Konsole, Gnome Terminal, kovidgoyal's kitty.
