### ISSUE TITLE
Explain ui rendering process

### ISSUE THREAD

**Issue by skabashnyuk** [elfmz/far2l#269]
I'm wonder to know how changes from internal buffer
are rendered with wxwidget on UI. For example 
this F7 dialog.  
<img width="772" alt="2017-03-29 14 02 58" src="https://cloud.githubusercontent.com/assets/1614429/24451947/a4fec6be-1489-11e7-9613-4b33017fc976.png">

I found that it's happening somewhere
around here https://github.com/elfmz/far2l/blob/c2f2b89db31b1c3cb9bed53267873f4cd7bc996d/far2l/keyboard.cpp#L767-L769
After  ScrBuf.Flush() during WINPORT(Sleep)(10); 
I assume it's made in some background thread. May be somewhere around Paint.cpp or Main.cpp.
But I wasn't able to catch it.
It would be nice if someone who know how structures like ScreenBuf goes to wxwidgets and eventually painted on canvas can explain how it's works

**Comment by elfmz** [comment]
I implemented windows console API - kind of lightweight cross-platform conemu, so FAR works as usually, just uses my functions instead of Windows's. All API declared in WinPort/WinPort.h, console-related APIs implemented in WinPort/src/APIConsole.cpp Then there're few abstractions for console buffers implemented in ConsoleInput.cpp/ConsoleOutput.cpp. 
wxWidgets painted implemented in Main.cpp/Paint.cpp and receives events from console API by implementing ConsoleOutputListener interface. Any console write causes OnConsoleOutputUpdated to be generated, so thats how wxWidgets know when to repaint region. And then, what to paint - it gets by querying corresponding area from ConsoleOutput, thats is singleton there - g_wx_con_out.
