### ISSUE TITLE
SCP plugin?

### ISSUE THREAD

**Issue by Angel996** [elfmz/far2l#407]
Hi.

Is it possible to use SCP plugin to access files on a remote host from inside Far Manager? Only FTP plugin is available by default. Running under Ubuntu 18.04.

thanks.

**Comment by singalen** [comment]
Duplicate of #86 (though not everybody is happy with gvfs).

**Comment by unxed** [comment]
It's actually #247 now :)

**Comment by singalen** [comment]
Should #86 then be named "scp/sftp support with gvfs/sshfs"?

**Comment by randolf** [comment]
@singalen I can confirm that I'm not entirely pleased with "gvfs" because I find it is slow for servers that are far away (NetBox in Far 3 on Windows is comparatively quick), and intermittently it also crashes and causes all instances of far2l to crash out when a connection to a remote file system is lost.

Aside from these problems, however, overall I'm very happy to have "gvfs" because it provides the functionality I need under Ubuntu Linux (which NetBox provides under Windows).

**Comment by unxed** [comment]
@randolf what about NetRocks in recent far2l? #247 
@Angel996 do you for sure need SCP, not SFTP?

**Comment by Angel996** [comment]
This has been solved a while ago, thank you.
