### ISSUE TITLE
No way to copy file name / command line contents on keyboards without a keypad Insert key

### ISSUE THREAD

**Issue by klotin** [elfmz/far2l#575]
How do I copy current file or text entered in the command line on Macbook ? Control-C / Command-C do not work - nothing happens.

At the same time, both - Control-V and Command-V work and paste just fine.

**Comment by elfmz** [comment]
Does Control-C works in Edit (some text file/F4 ) ?

**Comment by klotin** [comment]
Yep, both Control-C and Command-C copy text in Edit just fine

**Comment by singalen** [comment]
I actually have the same issue: there's no way on MacBook, without an external keyboard, to copy the contents of the command line, as it's only bound to Ctrl(Cmd)-KeypadInsert. Probably it's not even Mac-specific.

Doubling Ctrl(Cmd)-C for this purpose would be nice, as it doesn't do anything when a command is not running.

The more precise issue title would be: "No way to copy command line contents on keyboards without a keypad Insert key".

**Comment by elfmz** [comment]
Did you try hiding panels by Ctrl+O before doing copy?

**Comment by singalen** [comment]
It works, thanks a lot!
Is`Ctrl-C` supposed to change its function with panels on and off? In my perception, it only depends on the fact if a command is running in a foreground now.

**Comment by elfmz** [comment]
its original's FAR behavior (same in FAR 3)

**Comment by klotin** [comment]
I got so used to Ctrl-Insert that didn't realize Ctrl-C doesn't work on Windows either, so having no Insert key would be a problem for the original Far as well

I am closing the ticket

**Comment by singalen** [comment]
BTW, I would rather reopen the ticked and change the original behavior.
`Ctrl-C`/`Cmd-C` is a) a very popular function, and b) doesn't do anything else if panels are on, c) on laptops, which were not that popular in 1990s, there is no Insert key or it's inconveniently located.

To me, `Ctrl-C`/`Cmd-C` has become much more essential, because nowdays I have way more programs running that need clipboard integration.
