### ISSUE TITLE
Adding folder with files in archive deletes previous content of folder in archive

### ISSUE THREAD

**Issue by vasmedv** [elfmz/far2l#951]
After update far2l to 2.3.0 (20210302) from my old version 2020.06, adding files and folder in archive deletes previous content in folder and puts only new contents in folder, but i need only add and replace and no delete at all, as it was before update. How can i manage it? Can it be such option to enable? 
Also folder extracts without full path but only the target folder. I managed to return to full path extracting by removing -@%%R in zip extract command line, but maybe it could be option also?

**Comment by elfmz** [comment]
Regarding folder extracts not with full path - there was bug on full path and its actually valid&expected behaviour to extract only folder the same way as extraction works for files. So for now only option is to edit command line like you did, if there will be more requests like this - then checkbox in extract dialog could be possible too.
Regarding dir content replacement - its definately bug to be fixed.
